//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by SboCli.rc
//
#define IDD_SBOCLI_DIALOG               102
#define IDP_SOCKETS_INIT_FAILED         103
#define IDR_MAINFRAME                   128
#define IDD_MSGLOG                      129
#define IDD_CHAR_MODIFY                 130
#define IDD_BASE                        131
#define IDD_MAP_PARTS                   132
#define IDI_SBO                         135
#define IDD_PARTS_EDIT                  135
#define IDD_MAP_INFO                    136
#define IDD_PARTS_EDIT2                 137
#define IDD_MAP_SHADOW                  137
#define IDD_SHADOW_EDIT                 138
#define IDD_CHAR_ADMIN                  139
#define IDD_SERVER_INFO                 140
#define IDD_ITEM_LIST                   141
#define IDD_ITEM_NEW                    142
#define IDD_CHAR_ADDNPC                 143
#define IDD_CHAR_MODIFY_GRP             144
#define IDD_CHAR_MODIFY_ITEM            145
#define IDD_SELECT_ITEM                 146
#define IDD_ITEMTYPE_LIST               147
#define IDD_ITEMTYPE_NEW                148
#define IDD_CHAR_MOTION                 149
#define IDD_CHAR_MOTION_LIST            150
#define IDD_ITEMTYPE_NEW_ARMS           151
#define IDD_EFC_BALLOON_LIST            152
#define IDD_EFC_BALLOON                 153
#define IDD_CHAR_MOTIONTYPE_LIST        154
#define IDD_CHAR_ACCOUNTINFO            155
#define IDD_MAP_EVENT                   156
#define IDD_MAP_EVENT_BASE              157
#define IDD_MAP_EVENT_MOVE              158
#define IDD_MAP_EVENT_MOVE1             159
#define IDD_MAP_EVENT_NONE              159
#define IDD_EFC_EFFECT_LIST             160
#define IDD_EFC_EFFECT                  161
#define IDD_CHAR_MODIFY_TYPE_PUTNPC     162
#define IDD_CHAR_MODIFY_STATUS          163
#define IDB_TOOLBAR                     163
#define IDD_MAP_EVENT_MAPMOVE           164
#define IDD_ITEMWEAPONINFO_LIST         165
#define IDD_ITEMWEAPONINFO_NEW          166
#define IDD_SELECT_EFFECT               167
#define IDD_ITEMTYPE_NEW_HP             168
#define IDD_MAP_OBJECT                  169
#define IDD_MAP_OBJECT_EDIT             170
#define IDD_CHAR_MODIFY_STATUS1         171
#define IDD_SYSTEM_SET_INITCHARSTATUS   171
#define IDD_MAP_EVENT_INITSTATUS        172
#define IDD_MAP_EVENT_GRPIDTMP          173
#define IDD_ITEMTYPE_NEW_LIGHT          174
#define IDD_MAP_OBJECTDATA              175
#define IDD_MAP_OBJECTDATA_EDIT         176
#define IDD_TALK_SET                    177
#define IDD_CHAR_LIST                   178
#define IDD_CHAR_SKILL_LIST             179
#define IDD_CHAR_SKILL_BASE             180
#define IDD_CHAR_SKILL_NONE             181
#define IDD_MAP_EVENT_LIGHT             182
#define IDC_WEBBROWSER                  1000
#define IDC_ADD                         1000
#define IDC_ONLINE                      1001
#define IDC_MODIFY                      1001
#define IDC_CHARCOUNT                   1002
#define IDC_DELETE                      1002
#define IDM_ITEM_LIST                   1003
#define IDC_COPY                        1003
#define IDC_CHARNAME                    1004
#define IDC_FILTER                      1004
#define IDC_SEND                        1005
#define IDC_STATIC_CHARID               1006
#define IDC_ACCOUNTID                   1006
#define IDC_SEND2                       1007
#define IDC_LOG                         1010
#define IDC_COMBO1                      1011
#define IDC_TYPE                        1011
#define IDC_ADMINLEVEL                  1011
#define IDC_FAMILYTYPE                  1011
#define IDC_MOVETYPE                    1011
#define IDC_TYPE_CHAR                   1011
#define IDC_WALKMOTION                  1011
#define IDC_FRAME                       1012
#define IDC_DEL                         1012
#define IDC_MAPPARTS                    1012
#define IDC_TYPEGRPIDMAIN               1012
#define IDC_STANDMOTION                 1012
#define IDC_MOVETYPE2                   1012
#define IDC_SEX                         1012
#define IDC_HITTYPE                     1012
#define IDC_ID                          1013
#define IDC_DEL2                        1013
#define IDC_PLAY                        1013
#define IDC_TYPE2                       1013
#define IDC_USE                         1013
#define IDC_MSG                         1014
#define IDC_STOP                        1014
#define IDC_USE_PLAY                    1014
#define IDC_BASE                        1015
#define IDC_SCROLLBAR1                  1015
#define IDC_SCROLL                      1015
#define IDC_TYPE_PILE1                  1015
#define IDC_PILE                        1016
#define IDC_PREVIEW                     1017
#define IDC_TYPE_PILE2                  1017
#define IDC_TYPE_PILE3                  1018
#define IDC_NOW                         1021
#define IDC_COUNT                       1022
#define IDC_MAPSIZE                     1022
#define IDC_SLIDER                      1023
#define IDC_UP                          1023
#define IDC_VIEWTIME                    1024
#define IDC_DOWN                        1024
#define IDC_LEVEL                       1025
#define IDC_LEFT                        1025
#define IDC_VIEWPOS_Y1                  1025
#define IDC_RIGHT                       1026
#define IDC_LEVEL2                      1026
#define IDC_VALUE                       1027
#define IDC_VIEWPOS_X1                  1027
#define IDC_MAPID                       1028
#define IDC_VIEWPOS_X2                  1028
#define IDC_MAPNAME                     1029
#define IDC_VIEWPOS_Y2                  1029
#define IDC_CHANGEMAPNAME               1030
#define IDC_VIEWPOS_X3                  1030
#define IDC_TYPE_BLOCK                  1031
#define IDC_VIEWPOS_Y3                  1031
#define IDC_DARKLEVEL                   1031
#define IDC_TYPE_PILE                   1032
#define IDC_LEVEL3                      1032
#define IDC_TYPE_PILEBACK               1033
#define IDC_VIEWPOS_X0                  1033
#define IDC_BLOCK_UP                    1034
#define IDC_VIEWPOS_Y0                  1034
#define IDC_BLOCK_LEFT                  1035
#define IDC_BLOCK_RIGHT                 1036
#define IDC_BLOCK_DOWN                  1037
#define IDC_MOVE_UP                     1038
#define IDC_MOVE_DOWN                   1039
#define IDC_MOVE_LEFT                   1040
#define IDC_MOVE_RIGHT                  1041
#define IDC_MOVE_NONE                   1042
#define IDC_PARTS                       1043
#define IDC_LIST                        1044
#define IDC_OBJECT                      1044
#define IDC_GRP_PARTS                   1045
#define IDC_TYPE_DRAWLAST               1045
#define IDC_GRP_SHASOW                  1046
#define IDC_MAPSHADOW                   1046
#define IDC_ATTR                        1047
#define IDC_ATTR2                       1048
#define IDC_STATIC_ACCOUNTID            1048
#define IDC_STATIC_CHARNAME             1049
#define IDC_SAVE                        1049
#define IDC_SELECT_ITEMGRP              1052
#define IDC_NAME                        1053
#define IDC_SELECT_ITEMGRPSUB           1054
#define IDC_SELECT_ICONGRPID            1055
#define IDC_POSMAPID                    1057
#define IDC_POSX                        1058
#define IDC_POSY                        1059
#define IDC_POSX2                       1060
#define IDC_POSY2                       1061
#define IDC_GRPID                       1062
#define IDC_PUTON                       1063
#define IDC_BLOCK                       1064
#define IDC_DROPSOUNDID                 1064
#define IDC_PUSH                        1065
#define IDC_GRPIDSUB                    1065
#define IDC_EYE                         1066
#define IDC_ICONGRPID                   1066
#define IDC_EYECOLOR                    1067
#define IDC_RENEW                       1067
#define IDC_USESOUNDID                  1067
#define IDC_HAIR                        1068
#define IDC_USEEFFECTID                 1068
#define IDC_HAIRCOLOR                   1069
#define IDC_SP                          1070
#define IDC_NPC                         1071
#define IDC_ADDNEW                      1071
#define IDC_CLOTH                       1072
#define IDC_GRP_CHAR                    1075
#define IDC_GRP_PILE                    1076
#define IDC_GRP_PILE1                   1076
#define IDC_GRP_EFECT                   1077
#define IDC_GRP_PILE2                   1077
#define IDC_LOOP                        1078
#define IDC_GRP_PREVIEW                 1079
#define IDC_LEVEL1                      1080
#define IDC_REDRAWHAND                  1081
#define IDC_SOUNDID                     1082
#define IDC_SWING                       1083
#define IDC_GRP_PILE3                   1083
#define IDC_POKE                        1084
#define IDC_TYPEINFO                    1084
#define IDC_BOW                         1085
#define IDC_BUTTON1                     1085
#define IDC_PLAYSOUND                   1085
#define IDC_DRAW_UP                     1085
#define IDC_SET_MOVETYPE                1085
#define IDC_BLOW                        1086
#define IDC_GRP                         1086
#define IDC_BUTTON2                     1086
#define IDC_DRAW_DOWN                   1086
#define IDC_TALK                        1086
#define IDC_FISHING                     1087
#define IDC_LISTID                      1088
#define IDC_PROCID                      1089
#define IDC_EDIT1                       1091
#define IDC_MOTIONNAME                  1091
#define IDC_ACCOUNT                     1091
#define IDC_CHAT                        1091
#define IDC_DELAVERAGE                  1091
#define IDC_STAMINA                     1091
#define IDC_VALUE1                      1091
#define IDC_PASSWORD                    1092
#define IDC_RENEW_CLIENTVERSION         1092
#define IDC_EDIT2                       1092
#define IDC_MOVECOUNT                   1092
#define IDC_POWER                       1092
#define IDC_VALUE2                      1092
#define IDC_HIDE_MAINFRAME              1093
#define IDC_STRENGTH                    1093
#define IDC_MOTIONTYPE                  1094
#define IDC_MAGIC                       1094
#define IDC_SPIN_X1                     1095
#define IDC_SKILLFUL                    1095
#define IDC_COLOR                       1095
#define IDC_SPIN_Y1                     1096
#define IDC_ABILLITYAT                  1096
#define IDC_SPIN_X2                     1097
#define IDC_ABILLITYDF                  1097
#define IDC_SPIN_Y2                     1098
#define IDC_PATACK                      1098
#define IDC_SPIN_X3                     1099
#define IDC_PDEFENSE                    1099
#define IDC_SPIN_Y3                     1100
#define IDC_PMAGICDEFENSE               1100
#define IDC_DRAWLIST                    1101
#define IDC_PHITAVERAGE                 1101
#define IDC_EVENT                       1102
#define IDC_PAVOIDAVERAGE               1102
#define IDC_SPIN_X0                     1102
#define IDC_PUTCYCLE                    1103
#define IDC_PCRITICALAVERAGE            1103
#define IDC_SPIN_Y0                     1103
#define IDC_MAXPUTCOUNT                 1104
#define IDC_HP                          1104
#define IDC_SPIN_HIDEY                  1104
#define IDC_PUTAREA_X                   1105
#define IDC_MAXHP                       1105
#define IDC_PUTAREA_Y                   1106
#define IDC_MAXSP                       1106
#define IDC_PUTAVERAGE                  1107
#define IDC_DROPITEMAVERAGE             1107
#define IDC_LIST_NORMAL                 1107
#define IDC_MOVEAVERAGE                 1108
#define IDC_LIST_CRITICAL               1108
#define IDC_MOVEWAIT                    1109
#define IDC_ADD_NORMAL                  1109
#define IDC_DEL_NORMAL                  1110
#define IDC_MOVEAVERAGEBATTLE           1110
#define IDC_ADD_CRITICAL                1111
#define IDC_MOVEWAITBATTLE              1111
#define IDC_DEL_CRITICAL                1112
#define IDC_ATTR_FIRE                   1112
#define IDC_ATTR_WIND                   1113
#define IDC_WEAPONTYPE                  1114
#define IDC_ATTR_WATER                  1114
#define IDC_ATTR_EARTH                  1115
#define IDC_TARGET                      1115
#define IDC_ATTR_LIGHT                  1116
#define IDC_AREA                        1116
#define IDC_LOOPSOUND                   1116
#define IDC_EDIT19                      1117
#define IDC_ATTR_DARK                   1117
#define IDC_VIEWPOS_X                   1117
#define IDC_PMAGIC                      1118
#define IDC_LIGHTLEVEL                  1119
#define IDC_LIGHTTIME                   1120
#define IDC_TOPMOST                     1121
#define IDC_BGMID                       1122
#define IDC_WEATHERTYPE                 1123
#define IDC_DARK                        1125
#define IDC_EFFECTID                    1126
#define IDC_GRPNO                       1127
#define IDC_RADIO_OFF                   1128
#define IDC_RADIO_ON                    1129
#define IDC_IDMAIN                      1130
#define IDC_IDSUB                       1131
#define IDC_LEVEL_STA                   1132
#define IDC_LEVEL_STA2                  1133
#define IDC_VIEWTIME_STA                1134
#define IDC_VIEWTIME_STA2               1135
#define IDC_COUNT_STA                   1136
#define IDC_NOW_STA                     1137
#define IDC_PARTS_STA                   1138
#define IDC_CX                          1139
#define IDC_CY                          1140
#define IDC_HIDEY                       1141
#define IDC_LIGHT                       1141
#define IDC_HIT                         1142
#define IDC_DIRECTION                   1143
#define IDC_DROP                        1145
#define IDC_MAP                         1146
#define IDC_ENABLEBATTLE                1147
#define IDC_RECOVERY                    1148
#define IDC_TIME                        1149
#define IDM_CHAR_MODIFY                 32771
#define IDM_CHAR_LIST                   32772
#define IDM_MAP_PARTS                   32773
#define IDM_MAP_INFO                    32774
#define IDM_MAP_SHADOW                  32775
#define IDM_CHAR_ADMIN                  32776
#define IDM_SERVER_INFO                 32777
#define IDM_ITEM_TYPELIST               32778
#define IDM_ITEMTYPE_LIST               32778
#define IDM_CHAR_ADDNPC                 32779
#define IDM_CHAR_MODIFY_GRP             32780
#define IDM_CHAR_MODIFY_ITEM            32781
#define IDM_CHAR_MOTION                 32782
#define IDM_EFC_BALLOON_LIST            32783
#define IDM_DEBUG_GRID                  32784
#define IDM_CHAR_ACCOUNTINFO            32785
#define IDM_DEBUG_GRID_HALF             32786
#define IDM_DEBUG_GRID_OFF              32787
#define IDM_MAP_EVENT                   32788
#define IDM_EFC_EFFECT_LIST             32789
#define IDM_CHAR_MODIFY_STATUS          32790
#define IDM_DEBUG_MOVENOBLOCK           32791
#define ID_32792                        32792
#define IDM_MAP_ADD                     32793
#define ID_32794                        32794
#define IDM_ITEM_WEAPONINFO             32795
#define IDM_ITEM_WEAPONLIST             32796
#define ID_32797                        32797
#define IDM_MAP_OBJECT                  32798
#define ID_32799                        32799
#define IDM_MAP_WINDOW                  32800
#define ID_32801                        32801
#define ID_32802                        32802
#define IDM_SYSTEM_SET_CHARSTATUS_INIT  32803
#define IDM_SYSTEM_SET_INITCHARSTATUS   32804
#define ID_32805                        32805
#define IDM_MAP_OBJECTDATA              32806
#define ID_32807                        32807
#define ID_SKILL                        32808
#define ID_CHAR_SKILL                   32809
#define IDM_CHAR_SKILL                  32810

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        178
#define _APS_NEXT_COMMAND_VALUE         32811
#define _APS_NEXT_CONTROL_VALUE         1150
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
